//! `site stage-examples`: stage a pinned player and verified SDK builds into
//! Zola's static directory.
//!
//! Build the player with `site player` first, and build every listed SDK
//! example with `make disc`. This copies only the allowlisted EXEs, not the
//! demo disc or unrelated programs, and source revisions must match the pins.

use std::fs;
use std::path::PathBuf;
use std::process::Command;

use psoxide_link::sha256::sha256_hex;

use super::docs::{copy_file, copy_tree};
use super::{output, pins, require_pinned, site_root, text, write, Args};
use crate::obj;
use crate::pyjson::{dumps, Json};

fn digest(path: &std::path::Path) -> Result<String, String> {
    Ok(sha256_hex(
        &fs::read(path).map_err(|e| format!("{}: {e}", path.display()))?,
    ))
}

/// Copy the player and examples and write `static/examples/build.json`.
pub fn main(args: &[String]) -> Result<(), String> {
    let args = Args::parse(args, &[])?;
    let player_dir = PathBuf::from(args.need("player")?);
    let sdk = PathBuf::from(args.need("sdk")?);
    let examples_dir = PathBuf::from(args.need("examples")?);
    let site = site_root();
    let pins = pins()?;
    let record: serde_json::Value = serde_json::from_slice(
        &fs::read(player_dir.join("psoxide-player-build.json")).map_err(|e| e.to_string())?,
    )
    .map_err(|e| e.to_string())?;
    let emulator = record["emulator_revision"].as_str().unwrap_or_default();
    if record["emulator_dirty"].as_bool() != Some(false)
        || emulator != text(&pins, "emulator_revision")?
    {
        return Err("Player must be built from the clean pinned emulator revision".into());
    }
    // Website-only changes do not affect the pinned guest build.
    require_pinned(
        &sdk,
        text(&pins, "sdk_revision")?,
        &[
            "sdk",
            "crates",
            "assets",
            "tools",
            "Cargo.toml",
            "Cargo.lock",
            "rust-toolchain.toml",
            "Makefile",
        ],
    )?;
    for (name, expected) in record["files"]
        .as_object()
        .ok_or("player record has no files")?
    {
        let path = player_dir.join(name);
        if !path.is_file() || Some(digest(&path)?.as_str()) != expected["sha256"].as_str() {
            return Err(format!("Player integrity check failed: {name}"));
        }
    }
    let player = site.join("static/player");
    let examples = site.join("static/examples");
    if player.exists() {
        // Exclusively generated by this task.
        fs::remove_dir_all(&player).map_err(|e| e.to_string())?;
    }
    copy_tree(&player_dir, &player)?;
    fs::create_dir_all(&examples).map_err(|e| e.to_string())?;
    let mut files = Vec::new();
    for item in pins
        .get("example")
        .and_then(toml::Value::as_array)
        .ok_or("examples.toml lists no [[example]]")?
    {
        let name = format!(
            "{}.exe",
            item.get("name")
                .and_then(toml::Value::as_str)
                .ok_or("example without a name")?
        );
        let source = examples_dir.join(&name);
        let bytes = fs::read(&source).map_err(|e| format!("{}: {e}", source.display()))?;
        if !bytes.starts_with(b"PS-X EXE") {
            return Err(format!("Not a PS-X executable: {}", source.display()));
        }
        copy_file(&source, &examples.join(&name))?;
        files.push((
            name,
            obj! {"bytes" => bytes.len(), "sha256" => sha256_hex(&bytes)},
        ));
    }
    let sdk_revision = text(&pins, "sdk_revision")?;
    let staged = files.len();
    let manifest = obj! {
        "schema" => 1i64,
        "sdk_revision" => sdk_revision,
        "sdk_source" => format!("https://github.com/EBonura/PSoXide/tree/{sdk_revision}"),
        "emulator_revision" => emulator,
        "emulator_source" => format!("https://github.com/EBonura/PSoXide-emulator/tree/{emulator}"),
        "rustc" => output(Command::new("rustc").arg("-V").current_dir(&sdk))?,
        "build_command" => "make disc EXAMPLE=<name>",
        "files" => Json::Obj(files),
    };
    write(
        &examples.join("build.json"),
        dumps(&manifest, Some(2), true) + "\n",
    )?;
    println!("Staged {staged} examples and the pinned emulator player");
    Ok(())
}
