#!/usr/bin/env python3
"""Stage a pinned player and verified SDK builds into Zola's static directory.

Build the player with its own tools/build-web-player.py first, and build all six
SDK examples with make disc. This script copies only the six allowlisted EXEs,
not the demo disc or unrelated programs. Source revisions must match the pins.
"""
import argparse
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import tomllib

SITE = Path(__file__).resolve().parents[1]


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def run(*args, cwd):
    return subprocess.check_output(args, cwd=cwd, text=True).strip()


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--player', type=Path, required=True)
    ap.add_argument('--sdk', type=Path, required=True)
    ap.add_argument('--examples', type=Path, required=True)
    args = ap.parse_args()
    pins = tomllib.loads((SITE / 'data/examples.toml').read_text())
    record = json.loads((args.player / 'psoxide-player-build.json').read_text())
    if record['emulator_dirty'] or record['emulator_revision'] != pins['emulator_revision']:
        raise SystemExit('Player must be built from the clean pinned emulator revision')
    # Website-only changes do not affect the pinned guest build.
    subprocess.run(['git', 'diff', '--exit-code', pins['sdk_revision'], '--', 'sdk', 'crates', 'assets', 'tools', 'Cargo.toml', 'Cargo.lock', 'rust-toolchain.toml', 'Makefile'], cwd=args.sdk, check=True)
    for name, expected in record['files'].items():
        path = args.player / name
        if not path.is_file() or digest(path) != expected['sha256']:
            raise SystemExit(f'Player integrity check failed: {name}')
    player = SITE / 'static/player'
    examples = SITE / 'static/examples'
    if player.exists():
        shutil.rmtree(player)  # This is exclusively generated by this script.
    shutil.copytree(args.player, player)
    examples.mkdir(exist_ok=True)
    files = {}
    for item in pins['example']:
        name = item['name'] + '.exe'
        source = args.examples / name
        if source.read_bytes()[:8] != b'PS-X EXE':
            raise SystemExit(f'Not a PS-X executable: {source}')
        shutil.copy2(source, examples / name)
        files[name] = {'bytes': source.stat().st_size, 'sha256': digest(source)}
    manifest = {
        'schema': 1, 'sdk_revision': pins['sdk_revision'],
        'sdk_source': f"https://github.com/EBonura/PSoXide/tree/{pins['sdk_revision']}",
        'emulator_revision': record['emulator_revision'],
        'emulator_source': f"https://github.com/EBonura/PSoXide-emulator/tree/{record['emulator_revision']}",
        'rustc': run('rustc', '-V', cwd=args.sdk),
        'build_command': 'make disc EXAMPLE=<name>', 'files': files,
    }
    (examples / 'build.json').write_text(json.dumps(manifest, indent=2) + '\n')
    print(f'Staged {len(files)} examples and the pinned emulator player')


if __name__ == '__main__':
    main()
