#!/usr/bin/env python3
"""Convert vendored bitmap-font sources into Rust const byte
arrays in `../src/fonts/`. Run from the crate root:

    python3 tools/gen_fonts.py

Supports three source formats:

1. **dhepper/font8x8 C headers** (`.h`): the
   `char font8x8_<name>[N][8] = { { 0xHH, ... }, ... };` form.
   8×8 pixels, LSB-first.
2. **Raw IBM VGA BIOS dumps** (`.bin`): 256 glyphs × H bytes each,
   MSB-first, 8-pixel wide. 8×14 and 8×16 sizes come through this
   path.
3. **TrueType/OpenType fonts** (`.ttf`, `.otf`): rasterized through
   Pillow into a fixed-cell, 1bpp ASCII window suitable for PS1 UI.

Emits a `<PREFIX>_BITMAP: [u8; N*H*Bpr]` const plus a `BitmapFont`
descriptor referencing it. The generator is separate from
`build.rs` so generated Rust lands in source control — readable
diffs when fonts change, no build-script dependency on Python.

The historical bitmap paths are pure-Python3 stdlib. The TTF path needs
Pillow (`python3 -m pip install pillow`) because FreeType rasterization is
not available in the Python standard library.
"""

import math
import re
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:  # pragma: no cover - only hit when TTF entries are generated.
    Image = ImageDraw = ImageFont = None

CRATE_ROOT = Path(__file__).resolve().parent.parent
VENDOR = CRATE_ROOT / "vendor"
OUT = CRATE_ROOT / "src" / "fonts"

HEADER_BLOCK = '''// This file is GENERATED by `tools/gen_fonts.py` from
// `vendor/{source_name}`. Do NOT edit by hand — re-run the
// generator if the upstream font source changes.
//
// License: {license} (see `vendor/PROVENANCE.md`).

use crate::{{BitOrder, BitmapFont}};

'''

# Each entry is a dict so future source formats can add fields
# without breaking the shape. Required keys:
#
# - source:      path inside `vendor/`
# - format:      "c_header_8x8" | "ibm_bin" | "ttf"
# - mod:         Rust module name (filename in `src/fonts/`)
# - prefix:      const-name prefix (uppercased convention)
# - first_cp:    first codepoint covered by glyph 0
# - count:       number of glyphs
# - doc:         free-form docstring (trimmed per-line)
# - width / height / bit_order / advance / line_height:
#                optional overrides; `ibm_bin` defaults to 8×H MSB
#                and `c_header_8x8` defaults to 8×8 LSB.
FONTS = [
    {
        "source": "font8x8_basic.h",
        "format": "c_header_8x8",
        "mod": "basic",
        "prefix": "BASIC",
        "license": "Public Domain",
        "first_cp": 0x00,
        "count": 128,
        "doc": (
            "ASCII 0x00..0x7F — the printable range (0x20..0x7E) is "
            "the default for English + C-source text. Control-character "
            "glyphs (0x00..0x1F) are empty in dhepper's basic; use "
            "`font8x8_control` if you need visible control glyphs."
        ),
    },
    {
        "source": "font8x8_ext_latin.h",
        "format": "c_header_8x8",
        "mod": "ext_latin",
        "prefix": "EXT_LATIN",
        "license": "Public Domain",
        "first_cp": 0xA0,
        "count": 96,
        "doc": (
            "Latin-1 supplement, U+00A0..U+00FF (96 glyphs). Accented "
            "letters + currency + punctuation for Western European "
            "languages. dhepper's upstream calls this file `ext_latin` "
            "even though its codepoint range is the Latin-1 supplement. "
            "Pair with `BASIC` for a full Latin-1-capable atlas."
        ),
    },
    {
        "source": "font8x8_box.h",
        "format": "c_header_8x8",
        "mod": "boxdraw",
        "prefix": "BOXDRAW",
        "license": "Public Domain",
        "first_cp": 0x2500,
        "count": 128,
        "doc": (
            "Box-drawing U+2500..U+257F — single/double line corners and "
            "intersections. Handy for framing menus. (`box` is a reserved "
            "keyword in Rust, so the module is named `boxdraw`.)"
        ),
    },
    {
        "source": "IBM_VGA_8x16.bin",
        "format": "ibm_bin",
        "mod": "basic_8x16",
        "prefix": "BASIC_8X16",
        "license": "Public Domain",
        "first_cp": 0x00,
        "count": 128,  # ASCII + control window; caller can bump to 256 for full CP437
        "height": 16,
        "doc": (
            "IBM VGA 8×16 — the canonical BIOS console font every PC-era "
            "gamer recognises. ASCII range (0x00..0x7F), 16 rows per "
            "glyph, MSB-first within each byte. Pair with BASIC (8×8) for "
            "a small-body / large-heading ladder without re-uploading a "
            "single-size atlas. The full 256-glyph CP437 range (including "
            "box-drawing and extended symbols) is in the binary — we "
            "expose the lower 128 here to keep the atlas compact; trim "
            "`count` to 96 or extend to 256 by editing this table."
        ),
    },
]

TTF_FONT_DEFAULTS = {
    "format": "ttf",
    "first_cp": 0x20,
    "count": 96,
    "preferred_px": 16,
    "min_px": 8,
    "max_cell_w": 32,
    "max_cell_h": 16,
    "threshold": 128,
}

TTF_FONTS = [
    # Kenney Fonts, CC0.
    {
        "source": "kenney-fonts/Kenney Blocks.ttf",
        "mod": "kenney_blocks",
        "prefix": "KENNEY_BLOCKS",
        "license": "CC0-1.0",
        "doc": "Kenney Blocks, rasterized from Kenney Fonts. Chunky block display text for game UI.",
    },
    {
        "source": "kenney-fonts/Kenney Future.ttf",
        "mod": "kenney_future",
        "prefix": "KENNEY_FUTURE",
        "license": "CC0-1.0",
        "doc": "Kenney Future, rasterized from Kenney Fonts. Squared futuristic display text.",
    },
    {
        "source": "kenney-fonts/Kenney Future Narrow.ttf",
        "mod": "kenney_future_narrow",
        "prefix": "KENNEY_FUTURE_NARROW",
        "license": "CC0-1.0",
        "doc": "Kenney Future Narrow, rasterized from Kenney Fonts. Condensed sci-fi UI lettering.",
    },
    {
        "source": "kenney-fonts/Kenney High.ttf",
        "mod": "kenney_high",
        "prefix": "KENNEY_HIGH",
        "license": "CC0-1.0",
        "doc": "Kenney High, rasterized from Kenney Fonts. Tall arcade-style display lettering.",
    },
    {
        "source": "kenney-fonts/Kenney High Square.ttf",
        "mod": "kenney_high_square",
        "prefix": "KENNEY_HIGH_SQUARE",
        "license": "CC0-1.0",
        "doc": "Kenney High Square, rasterized from Kenney Fonts. Tall square arcade text.",
    },
    {
        "source": "kenney-fonts/Kenney Mini.ttf",
        "mod": "kenney_mini",
        "prefix": "KENNEY_MINI",
        "license": "CC0-1.0",
        "doc": "Kenney Mini, rasterized from Kenney Fonts. Compact readable UI lettering.",
    },
    {
        "source": "kenney-fonts/Kenney Mini Square.ttf",
        "mod": "kenney_mini_square",
        "prefix": "KENNEY_MINI_SQUARE",
        "license": "CC0-1.0",
        "doc": "Kenney Mini Square, rasterized from Kenney Fonts. Compact squared UI lettering.",
    },
    {
        "source": "kenney-fonts/Kenney Mini Square Mono.ttf",
        "mod": "kenney_mini_square_mono",
        "prefix": "KENNEY_MINI_SQUARE_MONO",
        "license": "CC0-1.0",
        "doc": "Kenney Mini Square Mono, rasterized from Kenney Fonts. Compact monospaced square UI text.",
    },
    {
        "source": "kenney-fonts/Kenney Pixel.ttf",
        "mod": "kenney_pixel",
        "prefix": "KENNEY_PIXEL",
        "license": "CC0-1.0",
        "doc": "Kenney Pixel, rasterized from Kenney Fonts. Pixel-art menu and HUD lettering.",
    },
    {
        "source": "kenney-fonts/Kenney Pixel Square.ttf",
        "mod": "kenney_pixel_square",
        "prefix": "KENNEY_PIXEL_SQUARE",
        "license": "CC0-1.0",
        "doc": "Kenney Pixel Square, rasterized from Kenney Fonts. Square pixel-art menu text.",
    },
    {
        "source": "kenney-fonts/Kenney Rocket.ttf",
        "mod": "kenney_rocket",
        "prefix": "KENNEY_ROCKET",
        "license": "CC0-1.0",
        "doc": "Kenney Rocket, rasterized from Kenney Fonts. Rounded sci-fi display lettering.",
    },
    {
        "source": "kenney-fonts/Kenney Rocket Square.ttf",
        "mod": "kenney_rocket_square",
        "prefix": "KENNEY_ROCKET_SQUARE",
        "license": "CC0-1.0",
        "doc": "Kenney Rocket Square, rasterized from Kenney Fonts. Square sci-fi display lettering.",
    },
    # Google Fonts, SIL OFL 1.1.
    {
        "source": "google-fonts/pressstart2p/PressStart2P-Regular.ttf",
        "mod": "press_start_2p",
        "prefix": "PRESS_START_2P",
        "license": "SIL OFL 1.1",
        "doc": "Press Start 2P, rasterized from Google Fonts. Arcade title/display lettering.",
    },
    {
        "source": "google-fonts/silkscreen/Silkscreen-Regular.ttf",
        "mod": "silkscreen",
        "prefix": "SILKSCREEN",
        "license": "SIL OFL 1.1",
        "doc": "Silkscreen, rasterized from Google Fonts. Crisp pixel-inspired UI lettering.",
    },
    {
        "source": "google-fonts/pixelifysans/PixelifySans[wght].ttf",
        "mod": "pixelify_sans",
        "prefix": "PIXELIFY_SANS",
        "license": "SIL OFL 1.1",
        "doc": "Pixelify Sans, rasterized from Google Fonts. Friendly pixel-display UI lettering.",
    },
    {
        "source": "google-fonts/orbitron/Orbitron[wght].ttf",
        "mod": "orbitron",
        "prefix": "ORBITRON",
        "license": "SIL OFL 1.1",
        "doc": "Orbitron, rasterized from Google Fonts. Geometric space-age sci-fi display text.",
    },
    {
        "source": "google-fonts/audiowide/Audiowide-Regular.ttf",
        "mod": "audiowide",
        "prefix": "AUDIOWIDE",
        "license": "SIL OFL 1.1",
        "doc": "Audiowide, rasterized from Google Fonts. Wide retro-futuristic cyber display text.",
    },
    {
        "source": "google-fonts/michroma/Michroma-Regular.ttf",
        "mod": "michroma",
        "prefix": "MICHROMA",
        "license": "SIL OFL 1.1",
        "doc": "Michroma, rasterized from Google Fonts. Clean technical sci-fi display text.",
    },
    {
        "source": "google-fonts/electrolize/Electrolize-Regular.ttf",
        "mod": "electrolize",
        "prefix": "ELECTROLIZE",
        "license": "SIL OFL 1.1",
        "doc": "Electrolize, rasterized from Google Fonts. Compact techno UI lettering.",
    },
    {
        "source": "google-fonts/oxanium/Oxanium[wght].ttf",
        "mod": "oxanium",
        "prefix": "OXANIUM",
        "license": "SIL OFL 1.1",
        "doc": "Oxanium, rasterized from Google Fonts. Squared sci-fi sans for UI labels.",
    },
    {
        "source": "google-fonts/rajdhani/Rajdhani-Regular.ttf",
        "mod": "rajdhani",
        "prefix": "RAJDHANI",
        "license": "SIL OFL 1.1",
        "doc": "Rajdhani, rasterized from Google Fonts. Condensed industrial UI lettering.",
    },
    {
        "source": "google-fonts/chakrapetch/ChakraPetch-Regular.ttf",
        "mod": "chakra_petch",
        "prefix": "CHAKRA_PETCH",
        "license": "SIL OFL 1.1",
        "doc": "Chakra Petch, rasterized from Google Fonts. Chamfered technical display text.",
    },
    {
        "source": "google-fonts/tektur/Tektur[wdth,wght].ttf",
        "mod": "tektur",
        "prefix": "TEKTUR",
        "license": "SIL OFL 1.1",
        "doc": "Tektur, rasterized from Google Fonts. Modular cyber UI lettering.",
    },
    {
        "source": "google-fonts/tomorrow/Tomorrow-Regular.ttf",
        "mod": "tomorrow",
        "prefix": "TOMORROW",
        "license": "SIL OFL 1.1",
        "doc": "Tomorrow, rasterized from Google Fonts. Modern rounded sci-fi UI lettering.",
    },
    {
        "source": "google-fonts/zendots/ZenDots-Regular.ttf",
        "mod": "zen_dots",
        "prefix": "ZEN_DOTS",
        "license": "SIL OFL 1.1",
        "doc": "Zen Dots, rasterized from Google Fonts. Decorative cyberpunk display lettering.",
    },
    {
        "source": "google-fonts/turretroad/TurretRoad-Regular.ttf",
        "mod": "turret_road",
        "prefix": "TURRET_ROAD",
        "license": "SIL OFL 1.1",
        "doc": "Turret Road, rasterized from Google Fonts. Mechanical sci-fi display text.",
    },
    {
        "source": "google-fonts/tiny5/Tiny5-Regular.ttf",
        "mod": "tiny5",
        "prefix": "TINY5",
        "license": "SIL OFL 1.1",
        "doc": "Tiny5, rasterized from Google Fonts. Small compact display lettering.",
    },
    {
        "source": "google-fonts/jersey10/Jersey10-Regular.ttf",
        "mod": "jersey_10",
        "prefix": "JERSEY_10",
        "license": "SIL OFL 1.1",
        "doc": "Jersey 10, rasterized from Google Fonts. Compact display lettering with arcade character.",
    },
    {
        "source": "google-fonts/spacemono/SpaceMono-Regular.ttf",
        "mod": "space_mono",
        "prefix": "SPACE_MONO",
        "license": "SIL OFL 1.1",
        "doc": "Space Mono, rasterized from Google Fonts. Technical monospace display text.",
    },
    {
        "source": "google-fonts/brunoace/BrunoAce-Regular.ttf",
        "mod": "bruno_ace",
        "prefix": "BRUNO_ACE",
        "license": "SIL OFL 1.1",
        "doc": "Bruno Ace, rasterized from Google Fonts. Wide techno-geometric cyber display text.",
    },
    {
        "source": "google-fonts/aldrich/Aldrich-Regular.ttf",
        "mod": "aldrich",
        "prefix": "ALDRICH",
        "license": "SIL OFL 1.1",
        "doc": "Aldrich, rasterized from Google Fonts. Squared sci-fi UI lettering.",
    },
    {
        "source": "google-fonts/syncopate/Syncopate-Regular.ttf",
        "mod": "syncopate",
        "prefix": "SYNCOPATE",
        "license": "Apache-2.0",
        "doc": "Syncopate, rasterized from Google Fonts. Wide unicase futuristic display text.",
    },
    {
        "source": "google-fonts/sharetechmono/ShareTechMono-Regular.ttf",
        "mod": "share_tech_mono",
        "prefix": "SHARE_TECH_MONO",
        "license": "SIL OFL 1.1",
        "doc": "Share Tech Mono, rasterized from Google Fonts. Monospace tech-console UI lettering.",
    },
    {
        "source": "google-fonts/jura/Jura[wght].ttf",
        "mod": "jura",
        "prefix": "JURA",
        "license": "SIL OFL 1.1",
        "doc": "Jura, rasterized from Google Fonts. Rounded technical sci-fi UI lettering.",
    },
]

FONTS.extend({**TTF_FONT_DEFAULTS, **entry} for entry in TTF_FONTS)


def parse_c_header_8x8(path: Path, expected_glyphs: int) -> list[list[int]]:
    """Parse dhepper's C array syntax:
        { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }
    """
    text = path.read_text()
    glyph_re = re.compile(
        r"\{\s*(0x[0-9a-fA-F]{2})\s*,\s*(0x[0-9a-fA-F]{2})\s*,\s*"
        r"(0x[0-9a-fA-F]{2})\s*,\s*(0x[0-9a-fA-F]{2})\s*,\s*"
        r"(0x[0-9a-fA-F]{2})\s*,\s*(0x[0-9a-fA-F]{2})\s*,\s*"
        r"(0x[0-9a-fA-F]{2})\s*,\s*(0x[0-9a-fA-F]{2})\s*\}"
    )
    glyphs = [[int(g, 16) for g in m.groups()] for m in glyph_re.finditer(text)]
    if len(glyphs) != expected_glyphs:
        raise SystemExit(
            f"{path.name}: parsed {len(glyphs)} glyphs, expected {expected_glyphs}"
        )
    return glyphs


def parse_ibm_bin(path: Path, height: int, expected_glyphs: int) -> list[list[int]]:
    """Parse IBM VGA ROM dump: `expected_glyphs × height` bytes,
    one byte per row, MSB-first bit order. Some dumps have 256
    glyphs and we take the first `expected_glyphs`.
    """
    data = path.read_bytes()
    total_glyphs_in_file = len(data) // height
    if total_glyphs_in_file < expected_glyphs:
        raise SystemExit(
            f"{path.name}: only {total_glyphs_in_file} glyphs in file, "
            f"needed {expected_glyphs}"
        )
    glyphs = []
    for gi in range(expected_glyphs):
        off = gi * height
        glyphs.append(list(data[off:off + height]))
    return glyphs


def parse_ttf(entry: dict, path: Path) -> list[list[int]]:
    """Rasterize a TrueType/OpenType font into fixed-size 1bpp glyph rows.

    The importer keeps a compact ASCII window (`first_cp..first_cp+count`) and
    searches down from `preferred_px` until every glyph's union bbox fits the
    configured cell. Each row is packed LSB-leftmost to match the generated
    `BitOrder::Lsb` descriptor.
    """
    if ImageFont is None:
        raise SystemExit(
            f"{path.name}: TTF import requires Pillow. Install with "
            "`python3 -m pip install pillow`."
        )
    if not path.is_file():
        raise SystemExit(f"missing font source: {path}")

    first_cp = entry["first_cp"]
    count = entry["count"]
    codes = list(range(first_cp, first_cp + count))
    threshold = entry.get("threshold", 128)
    pad = entry.get("pad", 1)
    max_cell_w = entry["max_cell_w"]
    max_cell_h = entry["max_cell_h"]
    min_px = entry.get("min_px", 8)
    preferred_px = entry.get("preferred_px", max_cell_h)

    chosen = None
    for px in range(preferred_px, min_px - 1, -1):
        font = ImageFont.truetype(str(path), px)
        bounds = [font.getbbox(chr(cp)) for cp in codes if cp != 0x20]
        bounds = [bbox for bbox in bounds if bbox is not None]
        if not bounds:
            raise SystemExit(f"{path.name}: no glyph bounds found")
        min_x = min(b[0] for b in bounds)
        min_y = min(b[1] for b in bounds)
        max_x = max(b[2] for b in bounds)
        max_y = max(b[3] for b in bounds)
        cell_w = max_x - min_x + pad * 2
        cell_h = max_y - min_y + pad * 2
        if cell_w <= max_cell_w and cell_h <= max_cell_h:
            chosen = (font, min_x, min_y, cell_w, cell_h)
            break
    if chosen is None:
        raise SystemExit(
            f"{path.name}: could not fit glyphs into {max_cell_w}x{max_cell_h} "
            f"cells down to {min_px}px"
        )

    font, min_x, min_y, cell_w, cell_h = chosen
    entry["width"] = cell_w
    entry["height"] = cell_h
    if "advance" not in entry:
        entry["advance"] = min(cell_w, max(1, math.ceil(font.getlength("M"))))
    entry["line_height"] = entry.get("line_height", cell_h)
    entry["advances"] = [
        min(255, max(1, math.ceil(font.getlength(chr(cp)))))
        for cp in codes
    ]

    row_bytes = (cell_w + 7) // 8
    glyphs = []
    for cp in codes:
        image = Image.new("L", (cell_w, cell_h), 0)
        draw = ImageDraw.Draw(image)
        if cp != 0x20:
            draw.text((pad - min_x, pad - min_y), chr(cp), font=font, fill=255)
        rows = []
        for y in range(cell_h):
            row = [0] * row_bytes
            for x in range(cell_w):
                if image.getpixel((x, y)) >= threshold:
                    row[x // 8] |= 1 << (x % 8)
            rows.extend(row)
        glyphs.append(rows)
    return glyphs


def emit_font_module(entry: dict, glyphs: list[list[int]]) -> str:
    source = entry["source"]
    prefix = entry["prefix"]
    mod = entry["mod"]
    first_cp = entry["first_cp"]
    count = entry["count"]
    doc = entry["doc"]
    license_name = entry.get("license", "Unknown")
    # Per-format defaults.
    if entry["format"] == "c_header_8x8":
        width, height = 8, 8
        bit_order = "Lsb"
    elif entry["format"] == "ibm_bin":
        width, height = 8, entry.get("height", 16)
        bit_order = "Msb"
    elif entry["format"] == "ttf":
        width = entry["width"]
        height = entry["height"]
        bit_order = "Lsb"
    else:
        raise SystemExit(f"unknown format: {entry['format']}")
    advance = entry.get("advance", width)
    line_height = entry.get("line_height", height)
    row_bytes = (width + 7) // 8
    total_bytes = count * row_bytes * height

    buf = [HEADER_BLOCK.format(source_name=source, license=license_name)]
    for line in doc.strip().split("\n"):
        line = line.lstrip()
        if line:
            buf.append(f"/// {line}\n")
        else:
            buf.append("///\n")
    buf.append(f"///\n")
    buf.append(
        f"/// {width}×{height} pixels per glyph, 1 bit per pixel, "
        f"{'LSB' if bit_order == 'Lsb' else 'MSB'} = leftmost.\n"
    )
    buf.append(f"pub const {prefix}_BITMAP: [u8; {total_bytes}] = [\n")
    for i, rows in enumerate(glyphs):
        cp = first_cp + i
        hex_row = ", ".join(f"0x{b:02x}" for b in rows)
        comment = f"U+{cp:04X}"
        if 0x20 <= cp <= 0x7E:
            comment += f" ({chr(cp)!r})"
        buf.append(f"    {hex_row}, // {comment}\n")
    buf.append("];\n\n")
    advances = entry.get("advances")
    if advances is not None:
        buf.append(
            f"/// Per-glyph pixel advances for the `{mod}` bitmap above.\n"
            f"pub const {prefix}_ADVANCES: [u8; {count}] = [\n"
        )
        for i in range(0, len(advances), 16):
            values = ", ".join(str(value) for value in advances[i:i + 16])
            buf.append(f"    {values},\n")
        buf.append("];\n\n")
    glyph_advances = f"Some(&{prefix}_ADVANCES)" if advances is not None else "None"
    buf.append(
        f"/// [`BitmapFont`] descriptor for the `{mod}` bitmap above.\n"
        f"/// Pass into [`crate::FontAtlas::upload`] to install it in VRAM.\n"
        f"pub const {prefix}: BitmapFont = BitmapFont {{\n"
        f"    glyph_w: {width},\n"
        f"    glyph_h: {height},\n"
        f"    first_char: 0x{first_cp:04x},\n"
        f"    glyph_count: {count},\n"
        f"    bitmap: &{prefix}_BITMAP,\n"
        f"    glyph_advances: {glyph_advances},\n"
        f"    advance_x: {advance},\n"
        f"    line_height: {line_height},\n"
        f"    bit_order: BitOrder::{bit_order},\n"
        f"}};\n"
    )
    return "".join(buf)


def parse_entry(entry: dict) -> list[list[int]]:
    path = VENDOR / entry["source"]
    if entry["format"] == "c_header_8x8":
        return parse_c_header_8x8(path, entry["count"])
    if entry["format"] == "ibm_bin":
        return parse_ibm_bin(path, entry.get("height", 16), entry["count"])
    if entry["format"] == "ttf":
        return parse_ttf(entry, path)
    raise SystemExit(f"unknown format: {entry['format']}")


def main() -> None:
    if not VENDOR.is_dir():
        raise SystemExit(f"missing vendor dir {VENDOR}")
    OUT.mkdir(parents=True, exist_ok=True)
    mod_lines = [
        "//! Built-in fonts.\n",
        "//!\n",
        "//! Mostly from dhepper/font8x8 (8×8 monochrome), the\n",
        "//! canonical IBM VGA 8×16 BIOS font, and a curated set of\n",
        "//! commercially usable TTFs rasterized into compact PS1 cells.\n",
        "//! See `vendor/PROVENANCE.md` for the full chain.\n",
        "//!\n",
        "//! Generated by `tools/gen_fonts.py`. Add new entries there\n",
        "//! rather than editing this file by hand.\n",
        "\n",
    ]
    for entry in FONTS:
        glyphs = parse_entry(entry)
        out_path = OUT / f"{entry['mod']}.rs"
        out_path.write_text(emit_font_module(entry, glyphs))
        print(
            f"wrote {out_path.relative_to(CRATE_ROOT)} — "
            f"{entry['count']} glyphs ({entry['format']})"
        )
        first_cp = entry["first_cp"]
        last_cp = first_cp + entry["count"] - 1
        mod_lines.append(
            f"/// Built-in font: `{entry['mod']}` "
            f"(U+{first_cp:04X}..U+{last_cp:04X}, "
            f"{entry['count']} glyphs).\n"
        )
        mod_lines.append(f"pub mod {entry['mod']};\n")
    mod_lines.append("\n")
    mod_lines.append("// Flat re-exports so call sites read as\n")
    mod_lines.append("// `psx_font::fonts::BASIC` etc.\n")
    for entry in FONTS:
        mod_lines.append(f"pub use {entry['mod']}::{entry['prefix']};\n")
    (OUT / "mod.rs").write_text("".join(mod_lines))
    print(f"wrote {(OUT / 'mod.rs').relative_to(CRATE_ROOT)}")


if __name__ == "__main__":
    main()
