#!/usr/bin/env python3
"""Turn the emulator's COMPATIBILITY.md into data/compat.json.

Usage:
    python3 scripts/import_compat.py [path/to/COMPATIBILITY.md]

Default input is data/compat-source.md, a verbatim copy of
PSoXide-emulator/docs/COMPATIBILITY.md. That file is itself generated by the
emulator's tools/compat_report.py from compat/*.toml. A future compat_report.py may emit JSON directly; for now this
parses the "Commercial discs" table. Game images are deliberately dropped:
the site shows names and results only.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SRC = ROOT / "data" / "compat-source.md"
OUT = ROOT / "data" / "compat.json"

TIERS = ["none", "boots", "intro", "menu", "in-game", "playable", "perfect"]


def cells(line):
    return [c.strip() for c in line.strip().strip("|").split("|")]


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    text = src.read_text()
    run_on = re.search(r"^Run on: (\S+)", text, re.M)
    section = text.split("## Commercial discs", 1)[1].split("\n## ", 1)[0]
    lines = [l for l in section.splitlines() if l.startswith("|")]
    header = cells(lines[0])
    games = []
    for line in lines[2:]:
        row = dict(zip(header, cells(line)))
        tier = row["PSoXide"]
        if tier not in TIERS:
            sys.exit(f"unknown tier {tier!r} in {row['Game']}")
        games.append({
            "name": row["Game"],
            "serial": row["Serial"],
            "region": row["Region"],
            "tier": tier,
            "bios_tier": row["Real BIOS (recorded)"],
            "fmv": row["FMV"],
            "issues": row["Known issues"],
            "measured_on": row["Measured on"],
            "evidence": row["Evidence"],
        })
    counts = {t: sum(1 for g in games if g["tier"] == t) for t in TIERS}
    data = {
        "source": "PSoXide-emulator docs/COMPATIBILITY.md",
        "run_on": run_on.group(1) if run_on else None,
        "tiers": TIERS,
        "counts": counts,
        "total": len(games),
        "games": games,
    }
    OUT.write_text(json.dumps(data, indent=1) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(games)} games, {counts}")


if __name__ == "__main__":
    main()
